### ISSUE TITLE
QML importPath functions

### ISSUE THREAD

**Issue by orbifx** [Kakadu/lablqt#22]
http://doc.qt.io/qt-5/qtqml-syntax-imports.html#qml-import-path

It would be nice to provide functions for adding paths for importing custom modules.

In the meantime a work-around is to set the `QML2_IMPORT_PATH` environment variable

**Comment by Kakadu** [comment]
Does the problem still exists when you load qml files through resource system?

**Comment by orbifx** [comment]
Not really a problem, a feature. Adding paths means cleaner QML which is independent of the file structure of the project.

**Comment by Kakadu** [comment]
@orbifx Can we close this?

**Comment by orbifx** [comment]
I think so. We have the function now. If there is a problem we can reopen or start new issue.
