### ISSUE TITLE
QVariant.of_float & QVariant.of_bool

### ISSUE THREAD

**Issue by orbifx** [Kakadu/lablqt#23]
It be handy if we could have a `QVariant.of_float`. I making due with either passing as string or a multiplied integer which then has to be divided.

Thanks.

**Comment by orbifx** [comment]
Added of_bool in the list, since they are similar.

**Comment by Kakadu** [comment]
@orbifx

**Comment by orbifx** [comment]
Lighting fast! I will use these in the next few days and get back. Thanks!

**Comment by orbifx** [comment]
I get an assertion failure:

> ASSERT failure in While converting OCaml value to QVariant: "Unknown variant tag", file propMap_stubs.c, line 84

The code here: https://github.com/Kakadu/lablqt/blob/master/lablqml/propMap_stubs.c#L84
doesn't seem to have the cases for these variants.

**Comment by orbifx** [comment]
I think this issue is fixed now.
