### ISSUE TITLE
PropMap callback implementation

### ISSUE THREAD

**Issue by orbifx** [Kakadu/lablqt#30]
Implement a flexible callback system for PropMap, supporing multiple instances with different callbacks.

Refer to:
- http://caml.inria.fr/pub/docs/manual-ocaml/intfc.html#sec424
- https://github.com/mrvn/ocaml-qt5/blob/master/src/qt5/src/Signal.h#L35
- https://github.com/mrvn/ocaml-qt5/blob/master/src/qt5/src/Connection_stubs.c

**Comment by Kakadu** [comment]
I do not really understand the description. Can you clarify this somehow @orbifx?

**Comment by orbifx** [comment]
I think this issue is outdated, irrelevant now. The QML property binding is a superior approach.
