### ISSUE TITLE
ETA of version compatible with 4.03?

### ISSUE THREAD

**Issue by bluddy** [Kakadu/lablqt#31]
The current version on OPAM has a constraint of < 4.03. 4.04 is around the corner. Any idea when the next version will be out?

**Comment by orbifx** [comment]
The git version is (should be) compatible with 4.03. I'm currently running it as such.

I don't have permissions to change the OPAM version, so until @Kakadu finds time, you could maybe build from source. It's not very hard.

**Comment by Kakadu** [comment]
Orbifx said everything correct.

**Comment by bluddy** [comment]
OK. I can pin opam to master, but it'd be nice to have a proper version whenever you get a chance. Not just for me, but for the ecosystem :)

**Comment by moll** [comment]
Stumbled upon the same issue. 👍

**Comment by Kakadu** [comment]
0.4 is in opam.
